name: build

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
      - '*.yml'
    branches:
      - master
      - release/*

jobs:
  scala-2_12:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup sbt
        uses: olafurpg/setup-scala@v5

      - name: run tests
        run: sbt ++ 2.12.10 compile

  scala-2_13:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup sbt
        uses: olafurpg/setup-scala@v5

      - name: run tests
        run: sbt ++ 2.12.10 compile