name: pr

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'

jobs:
  scala-2_12:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup sbt
        uses: olafurpg/setup-scala@v10

      - name: run tests
        run: sbt ++2.12.10 test

  scala-2_13:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup sbt
        uses: olafurpg/setup-scala@v10

      - name: run tests
        run: sbt ++2.13.3 test