name: pr_scala_3

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
    branches:
      - scala3/*

jobs:
  scala_3_0:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup sbt
        uses: olafurpg/setup-scala@v11

      - name: run tests
        run: sbt test
